variable "project" {
  description = <<-EOT
    Stable project identifier, shared by every environment in an account. Set once by
    the bootstrap stack. The legacy stack derived this two incompatible ways — a random
    4-character id in CloudFormation, and cksum(account-owner-region) in GitHub Actions
    — so images were pushed where Terraform never looked.
  EOT
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9-]{1,17}$", var.project))
    error_message = "project must be lowercase alphanumeric with hyphens, 2-18 characters. It prefixes IAM role names, which cap at 64; 18 leaves room for the longest service and role suffix."
  }
}

variable "env" {
  description = "Environment name. A first-class parameter; the legacy stack hardcoded \"dev\"."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9-]{0,9}$", var.env))
    error_message = "env must be lowercase alphanumeric with hyphens, up to 10 characters. Combined with project it feeds names with a 64-character ceiling; main.tf asserts the total."
  }
}

variable "region" {
  type = string
}

variable "flavour" {
  description = "Which flavour from flavours.yaml this environment takes."
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod", "ephemeral"], var.flavour)
    error_message = "flavour must be one of: dev, staging, prod, ephemeral."
  }
}

variable "flavour_overrides" {
  description = <<-EOT
    Per-key overrides merged over the chosen flavour. Shallow at the top level and one
    level into `rds` and `capacity`, which is enough to say "prod, but a bigger
    database" without forking a flavour.
  EOT
  type        = any
  default     = {}
}

variable "pod_ids" {
  description = <<-EOT
    Store pod identifiers. Generated by the bootstrap stack and read from SSM; set here
    only to pin them. Each pod is roughly a second small environment in cost terms —
    see the cost review.
  EOT
  type        = list(string)
  default     = null
}

variable "hosted_zone_id" {
  description = "Route53 zone. Read from SSM when not set here."
  type        = string
  default     = null
}

variable "image_tag" {
  description = "Container image tag to deploy. Read from SSM when not set here."
  type        = string
  default     = null
}

variable "dns_prefix" {
  description = <<-EOT
    Label every hostname of this environment sits under, so several environments can
    share one hosted zone. Defaults to the environment name, and to "" for prod, which
    owns the bare apex. The prereq root derives this identically and mints a matching
    certificate, so overriding it here means overriding it there too.
  EOT
  type        = string
  default     = null
}

variable "postgres_version" {
  description = <<-EOT
    RDS PostgreSQL engine version. Inherited from the legacy stack and not yet checked
    against what RDS actually offers in the target region — verify with
    `aws rds describe-db-engine-versions --engine postgres` before a first apply.
  EOT
  type        = string
  default     = "18.4"
}

variable "test_stores" {
  description = "Activates the test-stores Spring profile."
  type        = bool
  default     = false
}

variable "vpc_cidr_block" {
  type    = string
  default = "10.0.0.0/16"
}

variable "az_count" {
  type    = number
  default = 2
}
